[package]
name = "frand-home-base"

[package.version]
workspace = true
[package.authors]
workspace = true
[package.edition]
workspace = true

[dependencies]
frand-home-macro = { path = "../macro" }
serde = "1"
yew = "0.21"
log = "0.4.6"
