[workspace.package]
version = "0.3.0"
edition = "2021"
authors = [ "Frand <frand.nano@gmail.com>" ]
repository = "https://github.com/frand-nano/frand-home"

[workspace]
resolver = "2"
members = [ "source/actix", "source/yew" ]
default-members = [ "source/actix" ]