[music]
youtube_playlists = "https://www.googleapis.com/youtube/v3/playlists"
youtube_playlist_items = "https://www.googleapis.com/youtube/v3/playlistItems"
youtube_api_key = "" #youtube data api v3 key
youtube_playlists_max_results = 50
youtube_playlist_items_max_results = 50
playlist_items_max_results = 25
playlists = [
    { value = "PL4fGSI1pDJn6jXS_Tv_N9B8Z0HTRVJE0m" }, #Top 100 Songs South Korea
]